const ADD_FAVORITES = "ADD_FAVORITES";
const REMOVE_FAVORITES = "REMOVE_FAVORITES";
const GET_FAVORITES = "GET_FAVORITES";
const GET_MEETUPS = "GET_MEETUPS";
const ADD_MEETUPS = "ADD_MEETUPS";

export { ADD_FAVORITES, REMOVE_FAVORITES, GET_FAVORITES, GET_MEETUPS, ADD_MEETUPS };
